version: "3.3"

services:
  bot:
    build: .
    environment:
      DB_URI: '${DB_URI}'
      TOKEN: '${TOKEN}'
      DEBUG: '${DEBUG}'
      SPREADSHEET_ID: '${SPREADSHEET_ID}'
      FROM_CHAT_ID: '${FROM_CHAT_ID}'
      API_HASH: '${API_HASH}'
      API_ID: '${API_ID}'
    restart: always
    volumes:
      - ./bot.db:/app/bot.db
    logging:
        options:
            max-size: 1m
