version: "3.3"

services:
  bot:
    build: .
    environment:
      DB_URI: '${DB_URI}'
      TOKEN: '${TOKEN}'
      DEBUG: '${DEBUG}'
      SPREADSHEET_ID: '${SPREADSHEET_ID}'
    restart: always
#    volumes:
#      -
    logging:
        options:
            max-size: 1m
