version: "3.3"

services:
  db:
    image: postgis/postgis:14-3.2
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 1m
  bot:
    build: .
    environment:
      DB_URI: '${DB_URI}'
      TOKEN: '${TOKEN}'
      DEBUG: '${DEBUG}'
      RENT_SPREADSHEET_ID: '${RENT_SPREADSHEET_ID}'
      ADS_SHEET_ID: '${ADS_SHEET_ID}'
      ADS_SPREADSHEET_ID: '${ADS_SPREADSHEET_ID}'
      ADS_SHEET_NAME: '${ADS_SHEET_NAME}'
      FROM_CHAT_ID: '${FROM_CHAT_ID}'
      API_HASH: '${API_HASH}'
      API_ID: '${API_ID}'
      SENTRY_DSN: '${SENTRY_DSN}'
      SENTRY_ENV: '${SENTRY_ENV}'
      STATIC_FROM_CHAT_ID: '${STATIC_FROM_CHAT_ID}'
      WELCOME_VIDEO: '${WELCOME_VIDEO}'
      RENT_SHEET_ID: '${RENT_SHEET_ID}'
      G_MAPS_API: '${G_MAPS_API}'
      RENT_APARTMENTS_SHEET_NAME: '${RENT_APARTMENTS_SHEET_NAME}'


    restart: always
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    logging:
      options:
        max-size: 1m
    depends_on:
      - db
