"""empty message

Revision ID: 24765d8dd5e3
Revises: 658942f424d4
Create Date: 2022-08-01 16:39:58.495377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24765d8dd5e3'
down_revision = '658942f424d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('residential_complex', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('rent_price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    # ### end Alembic commands ###
