"""empty message

Revision ID: 658942f424d4
Revises: 
Create Date: 2022-07-31 15:42:50.897168

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '658942f424d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pk_type = sa.Integer()
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        pk_type = sa.BigInteger()

    op.create_table('users',
                    sa.Column('id', pk_type, nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('nickname', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
