"""empty message

Revision ID: 67e69262171e
Revises: 5598cc922016
Create Date: 2022-11-14 18:03:43.668467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e69262171e'
down_revision = '5598cc922016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('maps_link', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('maps_link', sa.String(), nullable=True))
    op.alter_column('apartments', 'street', nullable=False, new_column_name='address')
    op.alter_column('houses', 'placing', nullable=False, new_column_name='address')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'maps_link')
    op.drop_column('apartments', 'maps_link')
    op.alter_column('apartments', 'address', nullable=False, new_column_name='street')
    op.alter_column('houses', 'address', nullable=False, new_column_name='placing')

    # ### end Alembic commands ###
