"""empty message

Revision ID: bb482a6a3b67
Revises: 5676946e8510
Create Date: 2022-08-19 15:01:32.184339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb482a6a3b67'
down_revision = '5676946e8510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_text')
    # ### end Alembic commands ###
