"""empty message

Revision ID: c78c7304a0b9
Revises: 24765d8dd5e3
Create Date: 2022-08-01 21:54:05.423623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78c7304a0b9'
down_revision = '24765d8dd5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('placing', sa.String(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('living_area', sa.Integer(), nullable=False),
    sa.Column('territory_area', sa.Integer(), nullable=False),
    sa.Column('rent_price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
