"""empty message

Revision ID: d536b1a84536
Revises: bb482a6a3b67
Create Date: 2022-08-22 16:01:45.557358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd536b1a84536'
down_revision = 'bb482a6a3b67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('kids', sa.String(), nullable=True))
    op.add_column('apartments', sa.Column('pets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'pets')
    op.drop_column('apartments', 'kids')
    # ### end Alembic commands ###
